name: Build

on:
  pull_request: {}
  
  push:
    branches:
      - master
      - development
      - feature/github-pages

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

  schedule:
    # Trigger a weekly deploy in order to prevent build staleness in S3
    - cron: "0 0 * * 0"

# Ensure only the latest job runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Generate build artifacts

    runs-on: ubuntu-latest

    # Ensure that all commands run in the `packages/static/` directory
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup `pnpm`
        uses: pnpm/action-setup@v2
        with:
          version: "16.13.1"

      - name: Setup `node`
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm

      # This step will fail if `pnpm-lock.yaml` is missing or an update is needed
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Generate a production build
        run: |
          pnpm build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

      - name: export timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
     
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist/
  
  deploy:
    needs: build
    name: Deploy to GitHub Pages

    # Grant `GITHUB_TOKEN` the permissions required to deploy
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2