name: Build

on:
  pull_request: {}
  push:
    branches:
      - master
      - development
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.nvm
          key: nvm-${{ hashFiles('**.nvmrc') }}
      - name: install node
        shell: bash -l {0}
        run: nvm install --latest-npm
      - name: install dependencies
        run: /home/runner/.nvm/versions/node/v13.11.0/bin/npm install
      - name: build
        run: /home/runner/.nvm/versions/node/v13.11.0/bin/npm run build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      - name: export timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: export file name
        run: echo "FILENAME=$GIT_BRANCH_NAME-$TIMESTAMP" >> $GITHUB_ENV
      - name: pack build
        run: tar --create --gzip --file $FILENAME public
      - name: generate hash
        run: sha256sum $FILENAME > $TIMESTAMP.sha256
      - name: upload artifacts to s3
        run: aws s3 cp $FILENAME s3://static-sticky-builds
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
      # TODO: trigger a deploy
